#!/bin/bash
#
# Duplicate Files Cleanup Script
# Generated by Agent 5 - Duplicate Detection Specialist
# Date: 2026-01-08
#
# ⚠️  WARNING: This script will DELETE files. Review carefully before executing!
#
# Usage:
#   1. Review the script: cat DELETE_DUPLICATES.sh
#   2. Dry run (echo only): bash DELETE_DUPLICATES.sh --dry-run
#   3. Execute cleanup: bash DELETE_DUPLICATES.sh
#

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Counters
DELETED_COUNT=0
TOTAL_SIZE=0

# Function to print section headers
print_section() {
    echo ""
    echo -e "${GREEN}=== $1 ===${NC}"
    echo ""
}

# Function to delete file with logging
delete_file() {
    local file="$1"
    local reason="$2"

    if [ "$DRY_RUN" = "true" ]; then
        echo "[DRY RUN] Would delete: $file"
        echo "  Reason: $reason"
    else
        if [ -f "$file" ]; then
            local size=$(wc -c < "$file" 2>/dev/null || echo 0)
            rm "$file"
            echo "✓ Deleted: $file"
            echo "  Reason: $reason"
            DELETED_COUNT=$((DELETED_COUNT + 1))
            TOTAL_SIZE=$((TOTAL_SIZE + size))
        else
            echo "⚠ File not found: $file"
        fi
    fi
}

# Check for --dry-run flag
if [ "$1" = "--dry-run" ]; then
    DRY_RUN=true
    echo -e "${YELLOW}=== DRY RUN MODE - No files will be deleted ===${NC}"
fi

print_section "Phase 1: HIGH PRIORITY - Migrated .claude/ Files"

echo "Deleting 12 migrated command files from .legacy/.claude/commands/"
delete_file ".legacy/.claude/commands/kb-validate.md" "Migrated to domains/claude-code/commands/kb-validate.md"
delete_file ".legacy/.claude/commands/kb-search.md" "Migrated to domains/claude-code/commands/kb-search.md"
delete_file ".legacy/.claude/commands/add-hook.md" "Migrated to domains/claude-code/commands/add-hook.md"
delete_file ".legacy/.claude/commands/kb-query.md" "Migrated to domains/claude-code/commands/kb-query.md"
delete_file ".legacy/.claude/commands/retrospective.md" "Migrated to domains/claude-code/commands/retrospective.md"
delete_file ".legacy/.claude/commands/create-skill.md" "Migrated to domains/claude-code/commands/create-skill.md"
delete_file ".legacy/.claude/commands/kb-create.md" "Migrated to domains/claude-code/commands/kb-create.md"
delete_file ".legacy/.claude/commands/kb-index.md" "Migrated to domains/claude-code/commands/kb-index.md"
delete_file ".legacy/.claude/commands/review-claude-setup.md" "Migrated to domains/claude-code/commands/review-claude-setup.md"
delete_file ".legacy/.claude/commands/kb-sync.md" "Migrated to domains/claude-code/commands/kb-sync.md"

echo ""
echo "Deleting 7 migrated agent/subagent files from .legacy/.claude/agents/"
delete_file ".legacy/.claude/agents/kb-curator.md" "Migrated to domains/claude-code/agent-instructions/kb-curator.yaml"
delete_file ".legacy/.claude/agents/claude-code-expert.md" "Migrated to domains/claude-code/agent-instructions/claude-code-expert.yaml"
delete_file ".legacy/.claude/agents/subagents/README.md" "Migrated to domains/claude-code/agent-instructions/subagents/README.md"
delete_file ".legacy/.claude/agents/subagents/VALIDATOR.md" "Migrated to domains/claude-code/agent-instructions/subagents/VALIDATOR.md"
delete_file ".legacy/.claude/agents/subagents/KNOWLEDGE-CURATOR.md" "Migrated to domains/claude-code/agent-instructions/subagents/KNOWLEDGE-CURATOR.md"
delete_file ".legacy/.claude/agents/subagents/RESEARCHER.md" "Migrated to domains/claude-code/agent-instructions/subagents/RESEARCHER.md"
delete_file ".legacy/.claude/agents/subagents/DEBUGGER.md" "Migrated to domains/claude-code/agent-instructions/subagents/DEBUGGER.md"

# Delete empty subagents directory if it's now empty
if [ "$DRY_RUN" != "true" ] && [ -d ".legacy/.claude/agents/subagents" ]; then
    if [ -z "$(ls -A .legacy/.claude/agents/subagents 2>/dev/null)" ]; then
        rmdir ".legacy/.claude/agents/subagents" 2>/dev/null || true
        echo "✓ Removed empty directory: .legacy/.claude/agents/subagents"
    fi
fi

print_section "Phase 2: HIGH PRIORITY - Empty Placeholder Files"

echo "Deleting 2 empty placeholder files"
delete_file ".legacy/.claude/references/.gitkeep" "Empty file (0 bytes)"
delete_file ".legacy/.claude/standards-gitkeep.bak" "Empty backup file (0 bytes)"

print_section "Phase 3: MEDIUM PRIORITY - Translation Duplicates"

echo "Deleting 3 English translation files (-EN.md)"
delete_file ".legacy/docs/research/claude-code/CLAUDE-COMPLETE-PRACTICES-EN.md" "Translation duplicate, keeping CLAUDE-COMPLETE-PRACTICES.md"
delete_file ".legacy/docs/research/claude-code/CLAUDE-PERMISSION-MODES-GUIDE-EN.md" "Translation duplicate, keeping CLAUDE-PERMISSION-MODES-GUIDE.md"
delete_file ".legacy/docs/research/claude-code/CLAUDE-SLASH-COMMANDS-GUIDE-EN.md" "Translation duplicate, keeping CLAUDE-SLASH-COMMANDS-GUIDE.md"

echo ""
echo "Deleting 1 backup file"
delete_file ".legacy/docs/research/claude-code/CLAUDE-COMPLETE-PRACTICES.md.backup" "Backup file, original exists"

print_section "Phase 4: LOW PRIORITY - Version Iterations"

echo "Deleting older version of setup guide"
delete_file "docs/archive/QUICK_SETUP_CLAUDE.md" "Older version, keeping QUICK_SETUP_CLAUDE_FIXED.md"

print_section "PHASES 1-4 SUMMARY (SAFE CLEANUP)"

if [ "$DRY_RUN" = "true" ]; then
    echo -e "${YELLOW}DRY RUN COMPLETE${NC}"
    echo "Would delete ~27 files"
else
    echo "Files deleted: $DELETED_COUNT"
    echo "Total space freed: $TOTAL_SIZE bytes"
    echo ""
    echo -e "${GREEN}✓ Safe cleanup complete!${NC}"
    echo ""
    echo "Next steps:"
    echo "  1. Verify with: git status"
    echo "  2. Review changes: git diff --stat"
    echo "  3. Commit when ready: git add -A && git commit -m 'chore: Remove duplicate files'"
fi

echo ""
echo -e "${YELLOW}=== PHASE 5: MANUAL REVIEW REQUIRED ===${NC}"
echo ""
echo "The following files require MANUAL REVIEW before deletion:"
echo ""
echo "1. Documentation Overlaps (Review & Merge):"
echo "   - docs/archive/LOCAL-INSTALL-GUIDE.md vs docs/guides/installation/HARMONIZED-INSTALLATION-GUIDE.md"
echo "   - docs/archive/SETUP_GUIDE_FOR_CLAUDE.md vs docs/integration/for-claude-code/README.md"
echo "   - docs/archive/README_INTEGRATION.md vs docs/integration/for-projects/AGENT-INSTRUCTIONS.md"
echo "   - docs/archive/BOOTSTRAP-GUIDE.md vs docs/integration/BOOTSTRAP.md"
echo ""
echo "2. Legacy Research Docs (Verify YAML migration):"
echo "   - .legacy/docs/research/claude-code/claude-agents-guide.md"
echo "   - .legacy/docs/research/claude-code/claude-hooks-guide.md"
echo "   - .legacy/docs/research/claude-code/claude-skills-guide.md"
echo "   - .legacy/docs/research/claude-code/claude-claude-md-guide.md"
echo ""
echo "See DUPLICATE_DETECTION_SUMMARY.md for detailed instructions."
echo ""

# End of script
