meta:
  name: "Project Name"
  id: "project-slug"

stack:
  language: "python"
  framework: ""

sharing_criteria:
  universal_if:
    - "Generic Pattern"
    - "Library Fix"
    - "Tooling"
  project_specific_if:
    - "Business Logic"
    - "Secrets"
    - "Internal URLs"
